title : Guanhua Chen @ UW-Madison
author :
  name : Guanhua Chen
  email : gchen25@wisc.edu

theme: jekyll-theme-cayman
permalink : /:categories/:title 

# use redcarpet for syntax highlighting through github jekyll
# markdown : kramdown
  

# activate syntax highlighting 
# highlighter : rouge

# redcarpet:
#  extensions: []

kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
