title : Guanhua Chen @ UW-Madison
author :
  name : Guanhua Chen
  email : gchen25@wisc.edu

theme: jekyll-theme-cayman
permalink : /:categories/:title 

use redcarpet for syntax highlighting through github jekyll
markdown : kramdown
  

# activate syntax highlighting 
highlighter : rouge
